Create Cadastro_de_usuarios.md
restaurante-popular-catolicasc/docs pull request #15
Opened 2019-09-01 18:18 UTC by lourencofelipe

2019-09-03 16:37 UTC, henrilhos requested changes

2019-09-03 16:37 UTC, castilh0s commented on historias-de-usuarios/Cadastro de usuários.md
> +Cadastro de usuários
```suggestion
# Cadastro de usuários
```

2019-09-03 16:37 UTC, castilh0s commented on historias-de-usuarios/Cadastro de usuários.md
> +6. Eu como Comprador quero ter acesso do estoque e pedido de compra, cadastrar produtos e preços.
```suggestion
6. Eu como comprador quero ter as seguintes funcionalidades:
   1. Acesso ao estoque e pedido de compras;
   2. Cadastrar produtos e preços;
```

2019-09-03 16:37 UTC, castilh0s commented on historias-de-usuarios/Cadastro de usuários.md
> +E comparar preços e fornecedores.
```suggestion
   3. Comparar preços e fornecedores;
```

2019-09-03 16:37 UTC, castilh0s commented on historias-de-usuarios/Cadastro de usuários.md
> +E Cadastrar formas de pagamento.
```suggestion
   4. Cadastrar formas de pagamento;
```

2019-09-03 16:37 UTC, castilh0s commented on historias-de-usuarios/Cadastro de usuários.md
> +E Cadastrar e consultar fornecedores.
```suggestion
   5. Cadastrar e consultar fornecedores;
```

2019-09-03 16:37 UTC, castilh0s commented on historias-de-usuarios/Cadastro de usuários.md
> +E Emissão do pedido para compra.
```suggestion
   6. Emissão do pedido para compra;
```

2019-09-03 16:37 UTC, castilh0s commented on historias-de-usuarios/Cadastro de usuários.md
> +E também consultar as datas de recebimento.
```suggestion
   7. Consultar as datas de recebimento.
```

2019-09-03 16:37 UTC, castilh0s commented on historias-de-usuarios/Cadastro de usuários.md
> +
Apagar as linhas em branco

2019-09-03 16:38 UTC, henrilhos requested changes

2019-09-03 16:38 UTC, castilh0s commented on historias-de-usuarios/Cadastro de usuários.md
> +
Apagar espaços entre um tópico e o outro

2019-09-05 12:22 UTC, castilh0s commented
# Atenção

PR duplicado (ver #13)

2019-09-05 12:36 UTC, castilh0s commented
@restaurante-popular-catolicasc/lideres 

Mais alguém para fazer o CR, por favor

2019-09-06 23:34 UTC, murillo94 approved these changes

2019-09-07 23:10 UTC, henrilhos requested changes
Falta inserir o link para a história no `README.md`

2019-09-13 18:34 UTC, henrilhos requested changes

2019-09-13 18:34 UTC, castilh0s commented on README.md
> +2. [Cadastro de Usuários](historias-de-usuarios/Cadastro de usuários.md)
O nome do arquivo não pode ter espaços nem acentuação, ver o [guia de contribuição](https://github.com/restaurante-popular-catolicasc/docs/blob/master/CONTRIBUTING.md)

Sugiro alterar o nome do arquivo para `cadastro-usuarios.md`

2019-09-13 19:11 UTC, henrilhos approved these changes

2019-09-13 19:13 UTC, merged