Histórias de Usuários - Aprovação de Cardápios
restaurante-popular-catolicasc/docs pull request #21
Opened 2019-09-06 23:30 UTC by thiagocardosoca

## Descrição:

- Adicionada duas histórias de usuários envolvendo a aprovação dos cardápios para produção posteriormente.

## Issues relacionadas:
#18 

## Resolve:

- Mapeia _features_ a serem construídas a partir das histórias relacionadas.

2019-09-06 23:40 UTC, henrilhos requested changes
Recomendo fazer um documento só, chamado de `aprovacao-cardapios.md` com o seguinte conteúdo:

```md
# História de Aprovação de Cardápios

## Nutricionista (enviando cardápio aprovado para estoquista)

### Quero

- Enviar para o estoquista todos os todas os cardápios em lote para compra de alimentos e repasse para produção;
- Além disso quero programar envios de cardápios recorrentes para os dias em que os cardápios se repetem;
- Os cardápios devem ser encaminhados para email para o fiscal da prefeitura responsável, permitindo a troca do mesmo quando necessário.

### Para

Conseguir validar se os cardápios estão corretos e passar os cardápios para o time de produção;

### Definição de Pronto

Tela (pode ser a mesma de cardápios) que mostre todos os cardápios aprovados pela prefeitura porém que estão pendentes de envio para o estoquista, com botão para selecionar um ou vários cardápios e botão para fazer o envio dos cardápios em lote ou individual. Além disso a tela deve possuir filtro para filtrar entre cardápios aprovados e pendentes.

## Nutricionista (pedindo aprovação da prefeitura)

### Quero

- Enviar com apenas um clique solicitações de aprovação de cardápio para o fiscal da prefeitura, inclusive solicitações em lote;
- Além disso quero programar envios de cardápios recorrentes para os dias em que os cardápios se repetem;
- Os cardápios devem ser encaminhados para email para o fiscal da prefeitura responsável, permitindo a troca do mesmo quando necessário.

### Para

Conseguir validar se os cardápios estão corretos e passar os cardápios para o time de produção.

### Definição de Pronto

Tela com todos os cardápios cadastrados no sistema, com botão para selecionar um ou vários cardápios e botão para fazer o envio dos cardápios em lote ou individual. Além disso a tela deve possuir filtro para filtrar entre cardápios aprovados e pendentes.
```

Além disso adicionar URL para a história, [ver aqui](https://github.com/restaurante-popular-catolicasc/docs/blob/master/.github/CONTRIBUTING.md).

2019-09-07 00:02 UTC, henrilhos approved these changes

2019-09-07 00:20 UTC, rafaelmatsumoto requested changes

2019-09-07 00:20 UTC, rafaelmatsumoto commented on historias-de-usuarios/aprovacao-cardapios.md
> +Poder enviar a minha decição, com base na minha análise para a nutricíonista. Junto com um breve texto explicando o porque da minha decição caso o cardápio não seja aprovado.
Favor corrigir erros de ortografia

2019-09-07 00:20 UTC, rafaelmatsumoto commented on historias-de-usuarios/aprovacao-cardapios.md
> +Tela com um opção de "Aprovado" ou "Reprovado", junto a uma areá de tamanho médio para o texto explicativo, caso seja selecionado a opção "Reprovado".
Favor corrigir erros de ortografia

2019-09-07 00:20 UTC, rafaelmatsumoto commented on historias-de-usuarios/aprovacao-cardapios.md
> +Tela com todos os dados do cardápio incluindo os produtos, quantidade e valor para ánalise.
Favor corrigir erros de ortografia

2019-09-07 00:20 UTC, rafaelmatsumoto commented on historias-de-usuarios/aprovacao-cardapios.md
> +Uma tela online,com uma tabela contendo os dias de emisão dos cardápios, junto com o tipo do cardápio(mensal ou semanal), e o status (Já avaliado ou Falta avalião).
Favor corrigir erros de ortografia

2019-09-07 00:20 UTC, rafaelmatsumoto commented on historias-de-usuarios/aprovacao-cardapios.md
> +Uma tela online,com uma tabela contendo os dias de emisão dos cardápios, junto com o tipo do cardápio(mensal ou semanal), e o status (Já avaliado ou Falta avalião).
```suggestion
Uma tela online,com uma tabela contendo os dias de emissão dos cardápios, junto com o tipo do cardápio(mensal ou semanal), e o status (Já avaliado ou Falta avaliação).
```

2019-09-07 00:20 UTC, rafaelmatsumoto commented on historias-de-usuarios/aprovacao-cardapios.md
> +Tela com todos os dados do cardápio incluindo os produtos, quantidade e valor para ánalise.
```suggestion
Tela com todos os dados do cardápio incluindo os produtos, quantidade e valor para análise.
```

2019-09-07 00:20 UTC, rafaelmatsumoto commented on historias-de-usuarios/aprovacao-cardapios.md
> +Poder enviar a minha decição, com base na minha análise para a nutricíonista. Junto com um breve texto explicando o porque da minha decição caso o cardápio não seja aprovado.
```suggestion
Poder enviar a minha decisão, com base na minha análise para a nutricíonista. Junto com um breve texto explicando o porque da minha decisão caso o cardápio não seja aprovado.
```

2019-09-07 00:20 UTC, rafaelmatsumoto commented on historias-de-usuarios/aprovacao-cardapios.md
> +Tela com um opção de "Aprovado" ou "Reprovado", junto a uma areá de tamanho médio para o texto explicativo, caso seja selecionado a opção "Reprovado".
```suggestion
Tela com um opção de "Aprovado" ou "Reprovado", junto a uma área de tamanho médio para o texto explicativo, caso seja selecionado a opção "Reprovado".
```

2019-09-07 00:22 UTC, rafaelmatsumoto approved these changes

2019-09-07 00:22 UTC, merged