#8 - historia para ordem de compra
restaurante-popular-catolicasc/docs pull request #23
Opened 2019-09-07 00:10 UTC by ThuBitencourtt

## Descrição

 Foram criadas as histórias de ordem de compra 

## Issues relacionadas

Resolve #8 

## Informações adicionais

2019-09-07 00:17 UTC, LDinizz commented on historias-de-usuarios/ordem-de-compra.md
> +1. Eu como estoquista gostaria de enviar um relatório para o comprador.
Poderia especificar melhor o tipo de relatório à ser enviado para o comprador?

2019-09-07 00:19 UTC, LDinizz commented on historias-de-usuarios/ordem-de-compra.md
> +4. Eu como comprador gostaria de verificar o relatório de compras do estoquista.
O estoquista deverá informar manualmente a sua sugestão de compras para o comprador? Ou seja, solicitar que o comprador compre os Itens "A" , "B" e "C" ?

2019-09-07 00:19 UTC, henrilhos requested changes

2019-09-07 00:19 UTC, castilh0s commented on historias-de-usuarios/ordem-de-compra.md
> +### Eu como comprador:
```suggestion
## Eu como comprador:
```

2019-09-07 00:23 UTC, LDinizz commented on historias-de-usuarios/ordem-de-compra.md
> +3. Eu como um comprador gostaria de emitir relatórios mensais para verificar quantidades gastas por pedido.
Sugestão: Eu como comprador gostar de poder verificar no sistema os valores (R$ , Quantidade , Peso) que eu investi em cada pedido(s) de compra(s).

2019-09-07 00:27 UTC, LDinizz commented on historias-de-usuarios/ordem-de-compra.md
> +# Ordens de Preparo
TEste

2019-09-07 23:12 UTC, henrilhos requested changes
Falta inserir o link para a história no `README.md`

2019-09-13 23:09 UTC, henrilhos approved these changes
Link no README ok, talvez tenha algum conflito, mas aí só corrigir :wink:

2019-09-13 23:32 UTC, LDinizz approved these changes

2019-09-13 23:32 UTC, merged